branches:
 only:
  - master
  - main

os: linux
dist: focal
language: python
python: "3.8"
matrix:
  include:
    - arch: arm64-graviton2
      virt: vm
      group: edge
      env: CIBW_BUILD="cp39-manylinux_aarch64"
    - arch: arm64-graviton2
      virt: vm
      group: edge
      env: CIBW_BUILD="cp39-musllinux_aarch64"
    - arch: ppc64le
      env: CIBW_BUILD="cp39-manylinux_ppc64le"
    - arch: ppc64le
      env: CIBW_BUILD="cp39-musllinux_ppc64le"
    - arch: s390x
      env: CIBW_BUILD="cp39-manylinux_s390x"
    - arch: s390x
      env: CIBW_BUILD="cp39-musllinux_s390x"

install:
  - python -m pip install cibuildwheel==2.3.1
  - python -m pip install -r requirements-deploy.txt

script:
  - |
    set -e
    cibuildwheel --output-dir dist
    ls dist
    twine --version
    twine check --strict dist/*
