apt-get update && apt-get upgrade 
pkg install at
pkg install bc
pkg install binutils
pkg install binutils-bin
pkg install bk
pkg install c-script
pkg install clang
pkg install coreutils
pkg install cups
pkg install d8
pkg install dash
pkg install dx
pkg install ed
pkg install electric-fence
pkg install et
pkg install fd
pkg install fm
pkg install fx
pkg install gatling
pkg install gh
pkg install ghostscript
pkg install gn
pkg install golang
pkg install graphicsmagick
pkg install graphviz
pkg install gw
pkg install helix
pkg install hr
pkg install hstr
pkg install hz
pkg install i3
pkg install i3-gaps
pkg install iproute2
pkg install iw
pkg install jo
pkg install jq
pkg install kona
pkg install lf
pkg install libgnustep-base
pkg install libuber-h3
pkg install lr
pkg install m4
pkg install mc
pkg install mercury
pkg install mg
pkg install mono
pkg install moreutils
pkg install mtools
pkg install  mu
pkg install myrepos
pkg install  n-t-roff-sc
pkg install ne
pkg install netcat-openbsd
pkg install nss-utils
pkg install nushell
pkg install nxengine
pkg install o-editor
pkg install ol
pkg install p7zip
pkg install pari
pkg install pb
pkg install procps
pkg install proot-distro
pkg install pv
pkg install q-dns-client
pkg install radare2
pkg install rcs
pkg install rcshell
pkg install ripgrep
pkg install rq
pkg install ruby-ri
pkg install runit
pkg ibstall rw
pkg install sd
pkg install silversearcher-ag
pkg install sl
pkg install st
pkg install surfraw
pkg install task-spooler
pkg install tcllib
pkg install termux-am
pkg install termux-tools
pkg install texlive-bin
pkg install tin-summer
pkg install tinyfugue
pkg install ugrep
pkg ibstall up
pkg install util-linux
pkg install uucp
pkg install vim-gtk 
pkg install virustotal-cli
pkg install wireguard-tools
pkg install xh 
pkg install xorg-server 
pkg install xz-utils
pkg install yq 
pkg install z3 
pkg install zk
pkg install adb
pkg install textinfo  